[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
seraph = "9EK4NR8LwFBzV6jCNYoshQ9yyuM6yDxB8zsqrhTsK5z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/eliasmoreno/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
